### ISSUE TITLE
suggest to keep the original format of notes

### ISSUE THREAD

**Issue by donaldtone** [gaunthan/leanote2md#1]
just wonder if only export markdown to markdown, html to html?

**Comment by gaunthan** [comment]
Thanks for your suggestion! 

leanote2md currently only supports for exporting Markdown notes, which means HTML notes are not exported. 

But adding this feature is easy, all you need to do is (

1. modify the `exporter.py/save_note_as_md` function
2. remove the `if not note['IsMarkdown']` expression at line 120
3. determine the suffix of the note at line 147

We may include this feature in the future, if it works properly.

**Comment by donaldtone** [comment]
Thank you very much.
The html notes succeed output.
Anyway, the images fail to output. 
The linkages of images still look like that: 
```
<img id="__LEANOTE_D_IMG_1552878208040" src="http://localhost:9000/api/file/getImage?fileId=5c8f0a9f1de7082d6000004e" alt="" data-mce-src="/api/file/getImage?fileId=5c8f0a9f1de7082d6000004e">
```

**Comment by gaunthan** [comment]
> Thank you very much.
> The html notes succeed output.
> Anyway, the images fail to output.
> The linkages of images still look like that:
> 
> ```
> <img id="__LEANOTE_D_IMG_1552878208040" src="http://localhost:9000/api/file/getImage?fileId=5c8f0a9f1de7082d6000004e" alt="" data-mce-src="/api/file/getImage?fileId=5c8f0a9f1de7082d6000004e">
> ```

Thank you for the work!

The image are originally saved in the Leanote server. To properly export note, image link need to be change to an accessible URL. So we need to 

1. Download the image from Leanote (using Leanote API)  to local.
2. Upload the local image to image hosting website (e.g. Imgur, Flickr), which gives us a remotely accessible URL address. 
3. Use this URL address as the new value of attribute "src".

We are still wondering which image hosting websites are the best choice. so far as we known, they request an account for uploading image...
